# theme: jekyll-theme-cayman
remote_theme: lewismiddleton/cayman-dark
# theme: jekyll-theme-minimal
# theme: jekyll-theme-tactile
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-slate
# theme: jekyll-theme-time-machine
# theme: jekyll-theme-chalk
# title: ""
# description: "Description"
github:
  is_project_page: false